### ISSUE TITLE
New 2.6.6 on Azure Devops fails with File not found: '...2.6.6\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'

### ISSUE THREAD

**Issue by atumyio** [jessehouwing/azure-pipelines-tfvc-tasks#111]
Hi, we are using TFVC Check-in and it ran smoothly until today's update to 2.6.6. Now it fails with the error mentioned in the title. The pipeline is a pure dotnet CLI pipeline. Any ideas on how to solve the problem?

Thank you and best regards.

**Comment by monaelfalou** [comment]
Experiencing the same issue here. The fails started at the exact time the last update was pushed in.
PR: https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/pull/110

**Comment by jessehouwing** [comment]
2.6.7 is rolling out with an immediate fix.

**Comment by jessehouwing** [comment]
Had to switch over from classic to YAML due to changes in how I authenticate to my publisher (and my PAT tokens had expired) and in the conversion the step to make sure the powershell files were copied got dropped. Of course on my local test environment, those files were already there and didn't need copying.
