### ISSUE TITLE
Ability to check in a build output (.dll) back into source control at a specified location

### ISSUE THREAD

**Issue by glockster** [jessehouwing/azure-pipelines-tfvc-tasks#49]
Some time in the future we'll use NuGet for this but in the mean time we need a way to build a library whose output is a .dll that will be referenced by web services.  We want that .dll to be checked into source control so that a developer can do a get latest and pull it.  We'll do a CI build on that library anytime someone edits it, but we need to get the output into TFVC for the other developers to get.

**Comment by jessehouwing** [comment]
The vsts-tfvc-tasks support this. Just include a powershell script/batch
command to copy the dll to where you want it then use the tfvc checkin task
with the path to the file.

You may need to use the force option, as tfignore files by default ignore
*.dll.

**Comment by glockster** [comment]
Will the Add task allow us to do this?  I'd be first using a copy task to copy the .dll to the Libraries folder, but then need to somehow alert TFVC that a file needs to be checked in.  So far this isn't work.  I can see that the file is copied where I want it (at least the task reports success), however when using the Add task i receive an error stating that there isn't a workspace for the Libraries folder.  It's just a folder where we want all the .dlls deposited, so not a TFS project with an .sln file.

**Comment by jessehouwing** [comment]
If you want to check the files in, you must make sure the location is
mapped and sy chronicled during the build.

Map the folder in the build definition mapping.

On Aug 28, 2017 17:30, "glockster" <notifications@github.com> wrote:

Will the Add task allow us to do this? I'd be first using a copy task to
copy the .dll to the Libraries folder, but then need to somehow alert TFVC
that a file needs to be checked in. So far this isn't work. I can see that
the file is copied where I want it (at least the task reports success),
however when using the Add task i receive an error stating that there isn't
a workspace for the Libraries folder. It's just a folder where we want all
the .dlls deposited, so not a TFS project with an .sln file.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jessehouwing/vsts-tfvc-tasks/issues/49#issuecomment-325387196>,
or mute the thread
