### ISSUE TITLE
Add task returns "There is no working folder mapping for......" message and does nothing

### ISSUE THREAD

**Issue by aobubo856** [jessehouwing/azure-pipelines-tfvc-tasks#63]
Hi Jesse 

I wonder if you can help please? 

I am trying to add a zip file extracted as part of a build in the build artifact folder to a visual studio online/tfvc repository/project. I have added the "Add task" to the build process to add the file to the repository but it keeps returning the message "There is no working folder mapping for the targetfolderselected"

I think I am doing something wrong but not sure what to do. 

Below is how I have setup the Add task
![image](https://user-images.githubusercontent.com/35798134/37994730-537b95ac-320a-11e8-8e6d-654cec4d51f3.png)

Is the "Files to add" meant to specify the destination file and if so is the source of the files to add meant to be specified or is this above what these tasks are meant for?

![image](https://user-images.githubusercontent.com/35798134/37995126-4e9cd0b8-320b-11e8-91d6-fd701db03152.png)

![image](https://user-images.githubusercontent.com/35798134/37995069-33ea62da-320b-11e8-8694-4e4555b824af.png)

Many thanks in advance.

**Comment by jessehouwing** [comment]
The add task assumes there is a workspace mapping for the folder you're
adding to.

In order to achieve your purpose you need to add a folder mapping to the
build definitions get sources step. Then copy the files to the
sources/whatever you mapped folder and then run add.

In theory you could invoke `tf workfold` to map the artefacts directory,
but my tasks currently don't directly support this.

I've been working on, but not at rapid pace, a bunch of new build tasks for
tfvc that would Include a recipe to map&get additional files optionally in
a separate workspace.

**Comment by capuanodanilo** [comment]
How can I move a file from a location to other? I do not understand what screenshoot I will share...

**Comment by aobubo856** [comment]
Hi @jessehouwing ,
Thank you very much for your response. I managed to resolve it by mapping the folder under get sources as you suggested. The files are added and checked in to source control using the Add & Check In tasks 

![image](https://user-images.githubusercontent.com/35798134/38281522-ce265f10-37a2-11e8-8f6c-ce5a3cbf4bd5.png)

@capuanodanilo I use a copy task to move the zip into the sources directory

![image](https://user-images.githubusercontent.com/35798134/38281629-6191b6dc-37a3-11e8-86b3-134dc84ff4eb.png)

 and as the folder is mapped from above you only need to specify the file path in the add task

![image](https://user-images.githubusercontent.com/35798134/38281743-2036da72-37a4-11e8-904c-50fa64ebe1ca.png)

**Comment by jessehouwing** [comment]
Fixed
